### ISSUE TITLE
SSL on sending Mails through SMTP server?

### ISSUE THREAD

**Issue by larshei** [datamesh-manager/datamesh-manager-ce#1]
Love the idea of the datamesh-manager and 
just tried the it in a self-hosted docker-deployment using the latest docker image from half an hour ago.

I tried to add E-Mail sending and populated the SPRING_MAIL_... environment variables.

Our Mail-Server requires TLS, and when trying to send an E-Mail, I get the following error:

```
Failed messages: org.eclipse.angus.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail 
```

I did not find a way to check wether spring is configured to use ssl for sending mails or not.

Is SSL for SMTP enabled by default?
If not, how could I enable it?

**Comment by jochenchrist** [comment]
Glad to get that nice feedback :)

For Starttls, try to enable these variables to match your mail providers configuration:
```
SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
```

**Comment by larshei** [comment]
Thanks for the quick reply!

That solved the error :)

If i may hijack the issue for another question:
I got an email (username) configured, but it still tries to send mails as `hello@datamesh-manager.com`.

Is there a separate configuration for this?

**Comment by jochenchrist** [comment]
Great, and thanks for reporting, we‘ll implement a configuration option here, as the username might not always be an email address. I‘ll post an update here next week.

**Comment by larshei** [comment]
Thanks a lot!

**Comment by jochenchrist** [comment]
I added an option `DATAMESHMANAGER_MAIL_FROM ` (see README.md).
@larshei 
Please test and make sure to pull the latest image from docker hub.

**Comment by larshei** [comment]
Worked like a charm, many thanks!
