### ISSUE TITLE
datamesh-manager-ce, not any changes on Site after Login

### ISSUE THREAD

**Issue by WolfgangHolz** [datamesh-manager/datamesh-manager-ce#2]
Hi together, first: amazing work U did! But, after deploying in my local docker enviroment, I've the login page, can register, but after this nothimg happens, I can fill out the login page, it shows no error, but it stays there... Also after confirmation of the register mail, the same behavior... It happenms in every browser, yes, the cache was empty... can U pls help, I really wanna test this tool... Thanks a lot!

**Comment by jochenchrist** [comment]
I just checked with a fresh install, and could not reproduce.

Please select a slot here so that we can investigate together: https://calendly.com/jochenchrist/45min?month=2024-05

**Comment by jochenchrist** [comment]
Issue was resovled.
