### ISSUE TITLE
schema migration fails on external database

### ISSUE THREAD

**Issue by stephanheinze** [datamesh-manager/datamesh-manager-ce#3]
```
ERROR 1  --- [           main] o.f.core.internal.command.DbMigrate      : Migration of schema "dmm" to version "1.6 - create audittrail schema" failed! Changes successfully rolled back.
```
...
```
org.postgresql.util.PSQLException: ERROR: bind message supplies 0 parameters, but prepared statement "S_3" requires 2
```
Using `latest` image with ID 04b2147cb3d2. Please introduce version numbers and tags ;-)

External database servers identifies itself as:
```
PostgreSQL 11.22 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
```

**Comment by jochenchrist** [comment]
Hi @stephanheinze 

Data Mesh Manager requires PostgreSQL 14 or higher. Will add this to the documentation.

> Using latest image with ID 04b2147cb3d2. Please introduce version numbers and tags ;-)
Thanks for the feedback. We will discuss this.

**Comment by jochenchrist** [comment]
Added the requirements here: https://github.com/datamesh-manager/datamesh-manager-ce/blob/main/README.md#requirements

**Comment by stephanheinze** [comment]
Can't continue the evaluation because of the added requirements. 
No chance to get those postgreSQL extensions installed. 
What a pity, that was a promising approach.
